apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-example-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications

  source:
    repoURL: https://github.com/johnpaulnasc/multi-cloud-k8s-platform.git
    targetRevision: main
    path: kubernetes/apps/app-example/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: app-example

  syncPolicy:
    # Manual sync for production
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
