apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - required-labels.yaml
  - container-limits.yaml
  - allowed-repos.yaml
  - security-context.yaml
  - workload-best-practices.yaml
