apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yaml
  - allow-dns.yaml
  - ingress-to-apps.yaml
  - monitoring-access.yaml
  - egress-external.yaml
  - namespace-isolation.yaml
