apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sblockprivilegedcontainer
  annotations:
    description: "Blocks containers from running in privileged mode."
spec:
  crd:
    spec:
      names:
        kind: K8sBlockPrivilegedContainer
      validation:
        openAPIV3Schema:
          type: object
          properties:
            exemptImages:
              type: array
              description: "List of exempt container images"
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sblockprivilegedcontainer

        import future.keywords.in

        is_exempt(container) {
          exempt_images := object.get(input, ["parameters", "exemptImages"], [])
          img := container.image
          exemption := exempt_images[_]
          _matches_exemption(img, exemption)
        }

        _matches_exemption(img, exemption) {
          not endswith(exemption, "*")
          img == exemption
        }

        _matches_exemption(img, exemption) {
          endswith(exemption, "*")
          prefix := trim_suffix(exemption, "*")
          startswith(img, prefix)
        }

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          not is_exempt(container)
          container.securityContext.privileged == true
          msg := sprintf("Privileged container is not allowed: %v", [container.name])
        }

        violation[{"msg": msg}] {
          container := input.review.object.spec.initContainers[_]
          not is_exempt(container)
          container.securityContext.privileged == true
          msg := sprintf("Privileged init container is not allowed: %v", [container.name])
        }

        violation[{"msg": msg}] {
          container := input.review.object.spec.ephemeralContainers[_]
          not is_exempt(container)
          container.securityContext.privileged == true
          msg := sprintf("Privileged ephemeral container is not allowed: %v", [container.name])
        }
