apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - jaeger-all-in-one.yaml
  - otel-collector.yaml

commonLabels:
  app.kubernetes.io/part-of: observability-stack
  app.kubernetes.io/component: tracing
