apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - alertmanager-config.yaml
  - alertmanager-deployment.yaml
  - alertmanager-templates.yaml
  - ../rules/cluster-alerts.yaml

commonLabels:
  app.kubernetes.io/part-of: observability-stack
  app.kubernetes.io/component: alerting
