apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-rbac.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - kube-state-metrics.yaml
  - node-exporter.yaml

commonLabels:
  app.kubernetes.io/part-of: observability-stack
