apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0/manifests/install.yaml
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - projects/platform-project.yaml
  - projects/applications-project.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: --insecure
    target:
      kind: Deployment
      name: argocd-server
