apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - loki-config.yaml
  - loki-deployment.yaml
  - promtail.yaml

commonLabels:
  app.kubernetes.io/part-of: observability-stack
  app.kubernetes.io/component: logging
