apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - grafana-config.yaml
  - grafana-deployment.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - ../dashboards/cluster-overview.json
      - ../dashboards/multi-cloud-overview.json
      - ../dashboards/application-metrics.json

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/part-of: observability-stack
  app.kubernetes.io/component: visualization
