apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: security
spec:
  provider:
    vault:
      server: "https://vault.vault-system.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: security
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: security
spec:
  provider:
    oracle:
      vault: ""
      region: us-ashburn-1
      auth:
        secretRef:
          privatekey:
            name: oci-credentials
            namespace: external-secrets
            key: privateKey
          fingerprint:
            name: oci-credentials
            namespace: external-secrets
            key: fingerprint
          tenancy:
            name: oci-credentials
            namespace: external-secrets
            key: tenancy
          user:
            name: oci-credentials
            namespace: external-secrets
            key: user
