apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - namespace.yaml
  - external-secret-crds.yaml
  - service-account.yaml
  - cluster-secret-store.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: security
