apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-example
  namespace: app-example
  labels:
    app: app-example
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app-example.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-example
                port:
                  name: http
