apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-example
  namespace: app-example
  labels:
    app: app-example
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: app-example
