apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trivy-system

resources:
  - namespace.yaml
  - vulnerability-report-crd.yaml
  - trivy-operator-config.yaml
  - trivy-server.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: security
