apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vulnerabilityreports.aquasecurity.github.io
  labels:
    app.kubernetes.io/name: trivy-operator
spec:
  group: aquasecurity.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Repository
          type: string
          jsonPath: .report.artifact.repository
        - name: Tag
          type: string
          jsonPath: .report.artifact.tag
        - name: Scanner
          type: string
          jsonPath: .report.scanner.name
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Critical
          type: integer
          jsonPath: .report.summary.criticalCount
        - name: High
          type: integer
          jsonPath: .report.summary.highCount
        - name: Medium
          type: integer
          jsonPath: .report.summary.mediumCount
        - name: Low
          type: integer
          jsonPath: .report.summary.lowCount
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: vulnerabilityreports
    singular: vulnerabilityreport
    kind: VulnerabilityReport
    shortNames:
      - vuln
      - vulns
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configauditreports.aquasecurity.github.io
  labels:
    app.kubernetes.io/name: trivy-operator
spec:
  group: aquasecurity.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Scanner
          type: string
          jsonPath: .report.scanner.name
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Critical
          type: integer
          jsonPath: .report.summary.criticalCount
        - name: High
          type: integer
          jsonPath: .report.summary.highCount
        - name: Medium
          type: integer
          jsonPath: .report.summary.mediumCount
        - name: Low
          type: integer
          jsonPath: .report.summary.lowCount
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: configauditreports
    singular: configauditreport
    kind: ConfigAuditReport
    shortNames:
      - configaudit
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: exposedsecretreports.aquasecurity.github.io
  labels:
    app.kubernetes.io/name: trivy-operator
spec:
  group: aquasecurity.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Repository
          type: string
          jsonPath: .report.artifact.repository
        - name: Tag
          type: string
          jsonPath: .report.artifact.tag
        - name: Scanner
          type: string
          jsonPath: .report.scanner.name
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Critical
          type: integer
          jsonPath: .report.summary.criticalCount
        - name: High
          type: integer
          jsonPath: .report.summary.highCount
        - name: Medium
          type: integer
          jsonPath: .report.summary.mediumCount
        - name: Low
          type: integer
          jsonPath: .report.summary.lowCount
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: exposedsecretreports
    singular: exposedsecretreport
    kind: ExposedSecretReport
    shortNames:
      - exposedsecret
      - exposedsecrets
